# Generated by Django 2.1.3 on 2018-11-15 03:05

import disasterinfosite.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('disasterinfosite', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='embedsnugget',
            name='snugget_ptr',
            field=models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='disasterinfosite.Snugget'),
        ),
        migrations.AlterField(
            model_name='eq_fault_buffer',
            name='group',
            field=models.ForeignKey(default=disasterinfosite.models.EQ_Fault_Buffer.getGroup, on_delete=django.db.models.deletion.PROTECT, to='disasterinfosite.ShapefileGroup'),
        ),
    ]
