# Generated by Django 4.2.11 on 2024-06-27 19:44

import disasterinfosite.models
import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('disasterinfosite', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='preparednessaction',
            name='link',
        ),
        migrations.RemoveField(
            model_name='preparednessaction',
            name='link_text',
        ),
        migrations.AddField(
            model_name='dataoverviewimage',
            name='pdf',
            field=models.FileField(null=True, storage=disasterinfosite.models.OverwriteStorage(), upload_to='data'),
        ),
        migrations.AlterField(
            model_name='pasteventsphoto',
            name='image',
            field=models.ImageField(storage=disasterinfosite.models.OverwriteStorage(), upload_to='photos'),
        ),
        migrations.AlterField(
            model_name='snuggetsection',
            name='display_name',
            field=models.CharField(default='', help_text='The name to show for this section', max_length=100),
        ),
        migrations.AlterField(
            model_name='snuggetsection',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.CreateModel(
            name='WHP_FINAL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lookup_val', models.CharField(max_length=80)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
                ('groups', models.ManyToManyField(to='disasterinfosite.shapefilegroup')),
            ],
        ),
        migrations.CreateModel(
            name='Silverbow_co',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lookup_val', models.CharField(max_length=80)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
                ('groups', models.ManyToManyField(to='disasterinfosite.shapefilegroup')),
            ],
        ),
        migrations.CreateModel(
            name='Sanders_co',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lookup_val', models.CharField(max_length=80)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
                ('groups', models.ManyToManyField(to='disasterinfosite.shapefilegroup')),
            ],
        ),
        migrations.CreateModel(
            name='Ravalli_co',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lookup_val', models.CharField(max_length=80)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
                ('groups', models.ManyToManyField(to='disasterinfosite.shapefilegroup')),
            ],
        ),
        migrations.CreateModel(
            name='PreparednessLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(default='')),
                ('url', models.URLField(default='')),
                ('action', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='disasterinfosite.preparednessaction')),
            ],
        ),
        migrations.CreateModel(
            name='Missoula_co',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lookup_val', models.CharField(max_length=80)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
                ('groups', models.ManyToManyField(to='disasterinfosite.shapefilegroup')),
            ],
        ),
        migrations.CreateModel(
            name='Mineral_co',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lookup_val', models.CharField(max_length=80)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
                ('groups', models.ManyToManyField(to='disasterinfosite.shapefilegroup')),
            ],
        ),
        migrations.CreateModel(
            name='MergedEQs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lookup_val', models.IntegerField()),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
                ('groups', models.ManyToManyField(to='disasterinfosite.shapefilegroup')),
            ],
        ),
        migrations.CreateModel(
            name='Madison_co',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lookup_val', models.CharField(max_length=80)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
                ('groups', models.ManyToManyField(to='disasterinfosite.shapefilegroup')),
            ],
        ),
        migrations.CreateModel(
            name='Lincoln_co',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lookup_val', models.CharField(max_length=80)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
                ('groups', models.ManyToManyField(to='disasterinfosite.shapefilegroup')),
            ],
        ),
        migrations.CreateModel(
            name='Lake_co',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lookup_val', models.CharField(max_length=80)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
                ('groups', models.ManyToManyField(to='disasterinfosite.shapefilegroup')),
            ],
        ),
        migrations.CreateModel(
            name='Granite_co',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lookup_val', models.CharField(max_length=80)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
                ('groups', models.ManyToManyField(to='disasterinfosite.shapefilegroup')),
            ],
        ),
        migrations.CreateModel(
            name='Gallatin_co',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lookup_val', models.CharField(max_length=80)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
                ('groups', models.ManyToManyField(to='disasterinfosite.shapefilegroup')),
            ],
        ),
        migrations.CreateModel(
            name='FloodMaps_MT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lookup_val', models.CharField(max_length=80)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
                ('groups', models.ManyToManyField(to='disasterinfosite.shapefilegroup')),
            ],
        ),
        migrations.CreateModel(
            name='Flathead_co',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lookup_val', models.CharField(max_length=80)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
                ('groups', models.ManyToManyField(to='disasterinfosite.shapefilegroup')),
            ],
        ),
        migrations.CreateModel(
            name='fire_wui_wmt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lookup_val', models.CharField(max_length=80)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
                ('groups', models.ManyToManyField(to='disasterinfosite.shapefilegroup')),
            ],
        ),
        migrations.CreateModel(
            name='DeerLodge_co',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lookup_val', models.CharField(max_length=80)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
                ('groups', models.ManyToManyField(to='disasterinfosite.shapefilegroup')),
            ],
        ),
        migrations.CreateModel(
            name='CMZ_mt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lookup_val', models.CharField(max_length=80)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
                ('groups', models.ManyToManyField(to='disasterinfosite.shapefilegroup')),
            ],
        ),
        migrations.CreateModel(
            name='Burned_perimeter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lookup_val', models.CharField(max_length=80)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
                ('groups', models.ManyToManyField(to='disasterinfosite.shapefilegroup')),
            ],
        ),
        migrations.CreateModel(
            name='Beaverhead_co',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lookup_val', models.CharField(max_length=80)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
                ('groups', models.ManyToManyField(to='disasterinfosite.shapefilegroup')),
            ],
        ),
        migrations.CreateModel(
            name='AllCounties',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lookup_val', models.CharField(max_length=80)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
                ('groups', models.ManyToManyField(to='disasterinfosite.shapefilegroup')),
            ],
        ),
        migrations.AddField(
            model_name='snugget',
            name='AllCounties_filter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='disasterinfosite.allcounties'),
        ),
        migrations.AddField(
            model_name='snugget',
            name='Beaverhead_co_filter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='disasterinfosite.beaverhead_co'),
        ),
        migrations.AddField(
            model_name='snugget',
            name='Burned_perimeter_filter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='disasterinfosite.burned_perimeter'),
        ),
        migrations.AddField(
            model_name='snugget',
            name='CMZ_mt_filter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='disasterinfosite.cmz_mt'),
        ),
        migrations.AddField(
            model_name='snugget',
            name='DeerLodge_co_filter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='disasterinfosite.deerlodge_co'),
        ),
        migrations.AddField(
            model_name='snugget',
            name='Flathead_co_filter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='disasterinfosite.flathead_co'),
        ),
        migrations.AddField(
            model_name='snugget',
            name='FloodMaps_MT_filter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='disasterinfosite.floodmaps_mt'),
        ),
        migrations.AddField(
            model_name='snugget',
            name='Gallatin_co_filter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='disasterinfosite.gallatin_co'),
        ),
        migrations.AddField(
            model_name='snugget',
            name='Granite_co_filter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='disasterinfosite.granite_co'),
        ),
        migrations.AddField(
            model_name='snugget',
            name='Lake_co_filter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='disasterinfosite.lake_co'),
        ),
        migrations.AddField(
            model_name='snugget',
            name='Lincoln_co_filter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='disasterinfosite.lincoln_co'),
        ),
        migrations.AddField(
            model_name='snugget',
            name='Madison_co_filter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='disasterinfosite.madison_co'),
        ),
        migrations.AddField(
            model_name='snugget',
            name='MergedEQs_filter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='disasterinfosite.mergedeqs'),
        ),
        migrations.AddField(
            model_name='snugget',
            name='Mineral_co_filter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='disasterinfosite.mineral_co'),
        ),
        migrations.AddField(
            model_name='snugget',
            name='Missoula_co_filter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='disasterinfosite.missoula_co'),
        ),
        migrations.AddField(
            model_name='snugget',
            name='Ravalli_co_filter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='disasterinfosite.ravalli_co'),
        ),
        migrations.AddField(
            model_name='snugget',
            name='Sanders_co_filter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='disasterinfosite.sanders_co'),
        ),
        migrations.AddField(
            model_name='snugget',
            name='Silverbow_co_filter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='disasterinfosite.silverbow_co'),
        ),
        migrations.AddField(
            model_name='snugget',
            name='WHP_FINAL_filter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='disasterinfosite.whp_final'),
        ),
        migrations.AddField(
            model_name='snugget',
            name='fire_wui_wmt_filter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='disasterinfosite.fire_wui_wmt'),
        ),
    ]
