# Generated by Django 2.1.3 on 2018-11-15 03:10

import disasterinfosite.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('disasterinfosite', '0002_auto_20181115_0305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eq_fault_shaking',
            name='group',
            field=models.ForeignKey(default=disasterinfosite.models.EQ_Fault_Shaking.getGroup, on_delete=django.db.models.deletion.PROTECT, to='disasterinfosite.ShapefileGroup'),
        ),
    ]
