# Generated by Django 2.1.3 on 2019-01-17 05:37

import disasterinfosite.models
import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('disasterinfosite', '0002_auto_20181117_0138'),
    ]

    operations = [
        migrations.CreateModel(
            name='WildfireHazard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lookup_val', models.CharField(max_length=80)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
                ('group', models.ForeignKey(default=disasterinfosite.models.WildfireHazard.getGroup, on_delete=django.db.models.deletion.PROTECT, to='disasterinfosite.ShapefileGroup')),
            ],
        ),
        migrations.AddField(
            model_name='snugget',
            name='WildfireHazard_filter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='disasterinfosite.WildfireHazard'),
        ),
    ]
